CREATE TABLE requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  reference TEXT NOT NULL UNIQUE,
  course_code TEXT NOT NULL,
  course_title TEXT NOT NULL,
  exam_type TEXT NOT NULL,
  department TEXT NOT NULL,
  copies INTEGER NOT NULL CHECK (copies BETWEEN 1 AND 1000),
  pages INTEGER NOT NULL CHECK (pages BETWEEN 1 AND 100),
  exam_date TEXT NOT NULL,
  needed_by TEXT NOT NULL,
  notes TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'Submitted',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE status_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  request_id INTEGER NOT NULL REFERENCES requests(id) ON DELETE CASCADE,
  from_status TEXT,
  to_status TEXT NOT NULL,
  changed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
